<?php

namespace App\Filament\Resources\TracerStudies\Schemas;

use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Textarea;
use Filament\Schemas\Schema;

class TracerStudyForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('fakultas')
                    ->required(),
                TextInput::make('prodi')
                    ->required(),
                TextInput::make('thn_lulus')
                    ->numeric(),
                TextInput::make('nama')
                    ->required(),
                TextInput::make('domisili'),
                TextInput::make('daerah'),
                Textarea::make('alamat')
                    ->columnSpanFull(),
                TextInput::make('no_telp')
                    ->tel(),
                TextInput::make('mail'),
                Textarea::make('nik')
                    ->columnSpanFull(),
                TextInput::make('npwp'),
                TextInput::make('f8')
                    ->required(),
                TextInput::make('f504'),
                TextInput::make('f502'),
                TextInput::make('f505'),
                TextInput::make('f506'),
                TextInput::make('f5a1'),
                TextInput::make('f5a2'),
                TextInput::make('f1101'),
                TextInput::make('f1102'),
                TextInput::make('f5b'),
                TextInput::make('f5c'),
                TextInput::make('f5d'),
                TextInput::make('f18a'),
                TextInput::make('f18b'),
                TextInput::make('f18c'),
                DatePicker::make('f18d'),
                TextInput::make('f1201'),
                TextInput::make('f1202'),
                TextInput::make('f14'),
                TextInput::make('f15'),
                TextInput::make('f1761')
                    ->required(),
                TextInput::make('f1762')
                    ->required(),
                TextInput::make('f1763')
                    ->required(),
                TextInput::make('f1764')
                    ->required(),
                TextInput::make('f1765')
                    ->required(),
                TextInput::make('f1766')
                    ->required(),
                TextInput::make('f1767')
                    ->required(),
                TextInput::make('f1768')
                    ->required(),
                TextInput::make('f1769')
                    ->required(),
                TextInput::make('f1770')
                    ->required(),
                TextInput::make('f1771')
                    ->required(),
                TextInput::make('f1772')
                    ->required(),
                TextInput::make('f1773')
                    ->required(),
                TextInput::make('f1774')
                    ->required(),
                TextInput::make('f21')
                    ->required(),
                TextInput::make('f22')
                    ->required(),
                TextInput::make('f23')
                    ->required(),
                TextInput::make('f24')
                    ->required(),
                TextInput::make('f25')
                    ->required(),
                TextInput::make('f26')
                    ->required(),
                TextInput::make('f27')
                    ->required(),
                TextInput::make('f301'),
                TextInput::make('f302'),
                TextInput::make('f303'),
                TextInput::make('f401')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f402')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f403')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f404')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f405')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f406')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f407')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f408')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f409')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f410')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f411')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f412')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f413')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f414')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f415')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f416')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f6'),
                TextInput::make('f7'),
                TextInput::make('f7a'),
                TextInput::make('f1001'),
                TextInput::make('f1002'),
                TextInput::make('f1601')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f1602')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f1603')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f1604')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f1605')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f1606')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f1607')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f1608')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f1609')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f1610')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f1611')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f1612')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f1613')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('f1614')
                    ->required()
                    ->numeric()
                    ->default(0),
                DateTimePicker::make('timestamp')
                    ->required(),
            ]);
    }
}
